config/routes.rb
Rails.application.routes.draw do
  # root path
  root 'posts#index'

  # users
  get '/sign-up', to: 'users#new'
  post '/sign-up', to: 'users#create'

  get '/edit-account', to: 'users#edit'
  patch '/edit-account', to: 'users#update'

  delete '/delete-avatar', to: 'users#delete_avatar'
  delete '/delete-account', to: 'users#destroy'

  get '/feed', to: 'users#feed'

  resources :users, only: %i[index show] do
    member do
      get 'followings'
      get 'followers'
    end
  end

  # sessions
  get '/sign-in', to: 'sessions#new'
  post '/sign-in', to: 'sessions#create'
  delete '/sign-out', to: 'sessions#destroy'

  # posts
  get '/create-post', to: 'posts#new'
  post '/create-post', to: 'posts#create'

  resources :posts, only: %i[index
                             show
                             edit
                             update
                             destroy] do
    # post comments
    resources :comments, only: %i[edit create update destroy]

    # post likes
    post '/like', to: 'likes#create'
    delete '/unlike', to: 'likes#destroy'
    get '/likes', to: 'posts#likes'
  end

  # followings
  post '/follow/:id', to: 'followings#create', as: 'follow_user'
  delete '/unfollow/:id', to: 'followings#destroy', as: 'unfollow_user'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  # relations
  has_many :comments, dependent: :delete_all
  has_many :posts, dependent: :delete_all
  has_one_attached :avatar, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: 'follower_id',
                                  dependent: :destroy
  has_many :followings, through: :active_relationships,
                        source: :followed

  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: 'followed_id',
                                   dependent: :destroy
  has_many :followers, through: :passive_relationships,
                       source: :follower

  # scopes
  scope :by_created_at, ->(order) { order(created_at: order) }
  scope :with_attached_avatar, -> { includes(avatar_attachment: :blob) }

  # callbacks
  before_save { self.email.downcase! }

  # validations
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    length: { in: 5..70 },
                    uniqueness: true

  validates :nickname, presence: true,
                       length: { in: 3..40 },
                       uniqueness: true

  validates :biography, length: { maximum: 300 }

  validates :avatar, content_type: %i[png jpg jpeg gif],
                     size: { less_than: 5.megabytes },
                     limit: { max: 1 }

  validates :full_name, presence: true,
                        length: { in: 3..50 }

  # presence validation for password is not necessary
  # because has_secure_password automatically adds it
  validates :password, length: { in: 8..60 }

  validates :password_confirmation, presence: true,
                                    length: { in: 8..60 }
  # instance methods
  def delete_avatar
    self.avatar.purge
  end

  def follow(other_user)
    self.followings << other_user
  end

  def unfollow(other_user)
    self.followings.delete(other_user)
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def feed
    Post.with_user_with_attached_avatar
        .with_comments_with_user_with_attached_avatar
        .where(user_id: self.followings.ids)
        .by_created_at(:desc)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show followers followings]
  before_action :authorize_user!, only: %i[show followers followings]
  before_action :authorize_current_user!, only: %i[edit
                                                   update
                                                   destroy
                                                   delete_avatar]

  before_action :authorize_action!, only: %i[new
                                             create
                                             feed]

  def index
    @pagy, @users = pagy(User.with_attached_avatar
                             .by_created_at(:desc))
    authorize! @users
  end

  def followings
    @pagy, @users = pagy(@user.followings)
  end

  def followers
    @pagy, @users = pagy(@user.followers)
  end

  def feed
    @pagy, @posts = pagy(current_user.feed)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'You have successfully signed up'
      sign_in(@user)
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @pagy, @posts = pagy(@user.posts
                                .with_attached_images
                                .with_likes
                                .with_comments_with_user_with_attached_avatar
                                .by_created_at(:desc))
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      flash[:success] = 'You have successfully updated your account'
      redirect_to current_user
    else
      render :edit
    end
  end

  def destroy
    current_user.destroy
    flash[:success] = 'You have successfully deleted your account'
    sign_out
    redirect_to root_path
  end

  def delete_avatar
    if current_user.avatar.blank?
      # kostil' =)
      flash[:success] = 'You have successfully deleted your avatar'
      render :edit
    else
      current_user.delete_avatar
      flash[:success] = 'You have successfully deleted your avatar'
      redirect_to current_user
    end
  end

  private

  # should be called if action works with any user
  def set_user
    @user = User.find(params[:id])
  end

  # should be called if policy of action needs a variable
  def authorize_user!
    authorize! @user
  end

  # should be called if action works with current user
  def authorize_current_user!
    authorize! current_user, with: UserPolicy
  end

  # should be called if action must be authenticated
  # but does not have variable that policy needs to get
  def authorize_action!
    authorize! with: UserPolicy
  end

  def user_params
    params.require(:user).permit(:email,
                                 :nickname,
                                 :biography,
                                 :avatar,
                                 :full_name,
                                 :password,
                                 :password_confirmation)
  end
end

app/views/users/_avatar.html.slim
- unless user.avatar.blank?
  - unless user.avatar.content_type == 'image/gif'
    - if link
      = link_to user do
        = image_tag user.avatar.variant(resize_to_fill: [side, side]), class: 'avatar'
    - else 
      = image_tag user.avatar.variant(resize_to_fill: [side, side]), class: 'avatar'

  - else  
    - if link
      = link_to user do
        = image_tag user.avatar, width: side,
                                 height: side,
                                 class: 'avatar'
    - else
      = image_tag user.avatar, width: side,
                               height: side,
                               class: 'avatar'

- else
  - if link
    = link_to user do
      = image_tag 'avatar_placeholder.png', width: side,
                                            height: side,
                                            class: 'avatar'
  - else
    = image_tag 'avatar_placeholder.png', width: side,
                             height: side,
                             class: 'avatar'

app/views/users/_form.html.slim
= form_with url: url,
            model: user,
            class: 'form col-5' do |f|

  div.form-group.w-100
    = f.label :email, for: 'email-input'
    = f.email_field :email, class: "form-control w-100 #{field_has_error(user, :email)}",
                            id: "email-input",
                            aria: { describedly: 'email-help' },
                            placeholder: "example@gmail.com"
    = render 'shared/field_errors', model: user, field_name: :email

  div.form-group.w-100
    = f.label :nickname, for: 'nickname-input'
    = f.text_field :nickname, class: "form-control w-100 #{field_has_error(user, :nickname)}", 
                              id: "nickname-input",
                              aria: { describedly: 'nickname-help' },
                              placeholder: "username123"
    = render 'shared/field_errors', model: user, field_name: :nickname
  div.form-group.w-100
    = f.label :biography, for: 'biography-input'
    = f.text_area :biography, class: "form-control w-100 #{field_has_error(user, :biography)}", 
                              id: "biography-input",
                              aria: { describedly: 'biography-help' },
                              placeholder: "I am a new user :)"
    = render 'shared/field_errors', model: user, field_name: :biography

  div.form-group.w-100
    = f.label :avatar, for: 'avatar-input'
    = f.file_field :avatar, class: "form-control w-100 #{field_has_error(user, :avatar)}", 
                            id: "avatar-input",
                            aria: { describedly: 'avatar-help' }
    = render 'shared/field_errors', model: user, field_name: :avatar

    - if signed_in? && !user.avatar.blank?
      = link_to 'Delete Avatar', delete_avatar_path, method: :delete,
                                                     data: { confirm: 'Are you sure?' },
                                                     class: 'btn btn-primary submit-button--red',
                                                     style: 'margin-top: 1rem; float: none'


  div.form-group.w-100
    = f.label :full_name, 'Full Name', for: 'full_name-input'
    = f.text_field :full_name, class: "form-control w-100 #{field_has_error(user, :full_name)}", 
                               id: "full_name-input",
                               :'aria-describedby' => "full_name-help",
                               placeholder: "Sir User the Third"
    = render 'shared/field_errors', model: user, field_name: :full_name

  div.form-group.w-100
    = f.label :password, for: 'password-input'
    = f.password_field :password, class: "form-control w-100 #{field_has_error(user, :password)}", 
                                  id: "password-input",
                                  :'aria-describedby' => "password-help",
                                  placeholder: "********"
    = render 'shared/field_errors', model: user, field_name: :password

  div.form-group.w-100
    = f.label :password_confirmation, for: 'password_confirmation-input'
    = f.password_field :password_confirmation, class: "form-control w-100 #{field_has_error(user, :password_confirmation)}", 
                                  id: "password_confirmation-input",
                                  :'aria-describedby' => "password_confirmation-help",
                                  placeholder: "********"
    = render 'shared/field_errors', model: user, field_name: :password_confirmation
  
  - if page == :new
      div.w-100
        span Have an account already?   
        = link_to 'Sign In', sign_in_path
      = f.submit 'Create Account', class: 'btn btn-primary submit-button',
                                   style: 'margin-top: 0.5rem'
  - elsif page == :edit
      div.w-100
        = f.submit 'Update Account', class: 'btn btn-primary submit-button',
                                     style: 'margin-top: 0.5rem'
        - if signed_in?
          = link_to 'Delete Account', delete_account_path, method: :delete,
                                                           class: 'btn btn-primary submit-button--red',
                                                           style: 'margin-top: 0.5rem',
                                                           data: { confirm: 'All your data will be lost. Are you sure?' }                          

app/views/users/_user.html.slim
div.user-wrap.row
  div.col-4
    = render 'users/avatar', user: user, side: 200, link: true
    - unless user == current_user
      - if current_user.following?(user)
        = render 'followings/unfollow_button', user: user
      - else
        = render 'followings/follow_button', user: user
  div.col-7
    ul.list-group
      li.list-group-item 
        b Email: 
        = user.email
      li.list-group-item 
        b Nickname: 
        = user.nickname
      li.list-group-item 
        b Full Name: 
        = user.full_name

app/views/users/edit.html.slim
div.row.justify-content-center
  h1 Edit Account
  div.w-100

  = render 'users/form', user: current_user,
                         url: edit_account_path,
                         method: :patch,
                         page: :edit

app/views/users/feed.html.slim
div.row.justify-content-center
  - if @posts.any?
    h1 Feed
  - else
    h1 Feed
    div.w-100
    h2[style='margin-top: 1rem;'] Your feed is empty :(
  div.w-100
  div.col-9
    div.all-posts-wrap
      - if @posts.any?
        == pagy_bootstrap_nav(@pagy)
      - @posts.each_with_index do |post, index|
        = render 'posts/post', post: post,
                               post_index: index,
                               avatar_link: true,
                               page: :all_posts
      - if @posts.any?
        == pagy_bootstrap_nav(@pagy)                         

app/views/users/followers.html.slim
div.row.justify-content-center
  - if @user.followers.any?
    = content_tag(:h1, "#{@user.nickname}'s followers")
  - else  
    = content_tag(:h1, "#{@user.nickname}'s followers")
    div.w-100
    = content_tag(:h1, "#{@user.nickname} does not have any followers :(", style: 'margin-top: 1rem')
  div.w-100
  div.col-9
    - if @user.followers.any?
      == pagy_bootstrap_nav(@pagy)
      - @users.each do |user|
        = render user
    - if @user.followers.any?
      == pagy_bootstrap_nav(@pagy)          

app/views/users/followings.html.slim
div.row.justify-content-center
  - if @user.followings.any?
    = content_tag(:h1, "#{@user.nickname}'s followings")
  - else  
    = content_tag(:h1, "#{@user.nickname}'s followings")
    div.w-100
    = content_tag(:h1, "#{@user.nickname} does not have any followings :(", style: 'margin-top: 1rem')
  div.w-100
  div.col-9
    - if @user.followings.any?
      == pagy_bootstrap_nav(@pagy)
      - @users.each do |user|
        = render user
    - if @user.followings.any?
      == pagy_bootstrap_nav(@pagy)          

app/views/users/index.html.slim
div.row.justify-content-center
  h1 All Users
  div.w-100
  div.col-9
    div.all-users-wrap
      == pagy_bootstrap_nav(@pagy)
      - @users.each do |user|
        = render user
      == pagy_bootstrap_nav(@pagy)          

app/views/users/new.html.slim
div.row.justify-content-center
  h1 Sign Up
  div.w-100
  = render 'users/form', user: @user,
                         url: sign_up_path,
                         method: :post,
                         page: :new

app/views/users/show.html.slim
div.row.justify-content-center.account-card
  div.col-4
    h1 Account Info
    / user avatar
    = render 'users/avatar', user: @user, side: 200, link: false

    / follow/unfollow button
    - if signed_in?
      - if @user != current_user
        - if current_user.following?(@user)
          = render 'followings/unfollow_button', user: @user
        - else
          = render 'followings/follow_button', user: @user

    / followers and followings
    p
      = link_to "Followings: #{@user.followings.count}", followings_user_path(@user), class: 'followings-link'
      br
      = link_to "Followers: #{@user.followers.count}", followers_user_path(@user), class: 'followers-link'

    / user info
    ul
      li
        b ID: 
        = @user.id
      li
        b Email: 
        = @user.email
      li
        b Nickname: 
        = @user.nickname
      li
        b Full Name: 
        = @user.full_name
      - if @user.biography
        li
          b Bio: 
          = @user.biography  

  / user posts
  div.col-8
    - if @user == current_user
      h1[style='text-align: center;'] Your Posts
    - else
      h1[style='text-align: center;'] Posts
    div.user-posts-wrap
      - if @posts.any?
        == pagy_bootstrap_nav(@pagy)
      - else
        - if @user == current_user
          span[style='margin-top:3rem;font-size: 1.7rem;'] You still don't have any post :( Try to
          = link_to ' create one!', create_post_path, style: "font-size: 1.7rem;"
        - else
          span[style='margin-top:3rem; font-size: 1.7rem;'] This user didn't post anything yet      

      - @posts.each_with_index do |post, index|
        = render 'posts/post', post: post,
                               post_index: index,
                               avatar_link: false,
                               page: :user_posts
      - if @posts.any?
        == pagy_bootstrap_nav(@pagy)                         