config/routes.rb
Rails.application.routes.draw do
  # root path
  root 'posts#index'

  # users
  get '/sign-up', to: 'users#new'
  post '/sign-up', to: 'users#create'

  get '/edit-account', to: 'users#edit'
  patch '/edit-account', to: 'users#update'

  delete '/delete-avatar', to: 'users#delete_avatar'
  delete '/delete-account', to: 'users#destroy'

  get '/feed', to: 'users#feed'

  resources :users, only: %i[index show] do
    member do
      get 'followings'
      get 'followers'
    end
  end

  # sessions
  get '/sign-in', to: 'sessions#new'
  post '/sign-in', to: 'sessions#create'
  delete '/sign-out', to: 'sessions#destroy'

  # posts
  get '/create-post', to: 'posts#new'
  post '/create-post', to: 'posts#create'

  resources :posts, only: %i[index
                             show
                             edit
                             update
                             destroy] do
    # post comments
    resources :comments, only: %i[edit create update destroy]

    # post likes
    post '/like', to: 'likes#create'
    delete '/unlike', to: 'likes#destroy'
    get '/likes', to: 'posts#likes'
  end

  # followings
  post '/follow/:id', to: 'followings#create', as: 'follow_user'
  delete '/unfollow/:id', to: 'followings#destroy', as: 'unfollow_user'
end

app/models/post.rb
class Post < ApplicationRecord
  # relations
  belongs_to :user
  has_many :comments, dependent: :delete_all
  has_many :likes, dependent: :delete_all
  has_many_attached :images, dependent: :delete_all

  # scopes
  scope :with_user_with_attached_avatar,
        -> { includes(:user).merge(User.with_attached_avatar) }
  scope :with_attached_images, -> { includes(images_attachments: :blob) }
  scope :with_likes, -> { includes(:likes) }
  scope :with_comments_with_user_with_attached_avatar,
        -> { includes(:comments).merge(Comment.with_user_with_attached_avatar) }
  scope :by_created_at, ->(order) { order(created_at: order) }

  # validations
  validates :user_id, presence: true
  validates :content, length: { maximum: 200 }
  validates :images, attached: true,
                     content_type: %i[png jpg jpeg gif],
                     size: { less_than: 3.megabytes },
                     limit: { min: 1, max: 10 }
  
  # instance methods
  def created_at_formatted
    self.created_at.strftime("%d/%m/%Y at %H:%M")
  end

  def liked_by_user?(user)
    self.likes.find_by(user_id: user.id)
  end

  def like_by(user)
    self.likes << Like.new(post_id: self.id,
                           user_id: user.id)
  end

  def unlike_by(user)
    like = self.likes.find_by(user_id: user.id)
    self.likes.delete(like)
  end

  def liked_users
    User.where(id: self.likes.pluck(:user_id))
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authorize_action!, only: %i[edit update destroy likes new create]
  before_action :set_current_user_post, only: %i[edit update destroy]
  # before_action :authorize_post!, only: %i[edit update destroy]

  def index
    @pagy, @posts = pagy(Post.with_user_with_attached_avatar
                             .with_attached_images
                             .with_likes
                             .with_comments_with_user_with_attached_avatar
                             .by_created_at(:desc))

    authorize! @posts
  end

  def likes
    @post = Post.find(params[:post_id])

    @pagy, @users = pagy(@post.liked_users.with_attached_avatar)
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = 'You have successfully created new post'
      redirect_to @post
    else
      render :new
    end
  end

  def show
    @post = Post.with_comments_with_user_with_attached_avatar.find(params[:id])
    authorize! @post
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
      flash[:success] = 'You have successfully updated your post'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:success] = 'You have successfully deleted your post'
    redirect_to @post.user
  end

  private

  # should be called if action works with any user's post
  # def set_post
  #   @post = Post.find(params[:id])
  # end

  # should be called if action works with current user's post
  def set_current_user_post
    @post = current_user.posts.find(params[:id])
  end

  # should be called if policy of action needs a variable
  def authorize_post!
    authorize! @post
  end

  # should be called if action must be authenticated
  # but does not have variable that policy needs to get
  def authorize_action!
    authorize! with: PostPolicy
  end

  def post_params
    params.require(:post).permit(:content, images: [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_belongs_to_current_user?(post)
    post.user == current_user
  end

  def post_with_username_link?(page)
    pages_with_username_link = %i[all_posts post]

    pages_with_username_link.include?(page)
  end

  def post_with_avatar_link?(page)
    pages_with_avatar_link = %i[all_posts post]

    pages_with_avatar_link.include?(page)
  end
end

app/views/posts/_form.html.slim
= form_with url: url,
            model: post,
            class: 'form col-5' do |f|

  div.form-group.w-100
    = f.label :content, for: 'content-input'
    = f.text_area :content, class: "form-control w-100 #{field_has_error(post, :content)}",
                            id: "content-input",
                            aria: { describedly: 'content-help' },
                            placeholder: "My new cool post!"
    = render 'shared/field_errors', model: post, field_name: :content

  div.form-group.w-100
    = f.label :images, for: 'images-input'
    = f.file_field :images, multiple: true,
                            accept: 'image/jpg,image/jpeg,image/png,image/gif',
                            class: "form-control w-100 #{field_has_error(post, :images)}",
                            id: "images-input",
                            aria: { describedly: 'images-help' }
    = render 'shared/field_errors', model: post, field_name: :images

  - if page == :new
      div.w-100
        = f.submit 'Create Post', class: 'btn btn-primary submit-button',
                                  style: 'margin-top: 0.5rem'
  - elsif page == :edit
      div.w-100
        = f.submit 'Update Post', class: 'btn btn-primary submit-button',
                                  style: 'margin-top: 0.5rem'

app/views/posts/_post.html.slim
div.post-wrap
  = render 'users/avatar', user: post.user, side: 50, link: post_with_avatar_link?(page)
  - if post_with_username_link?(page)
    span.user-nickname = link_to post.user.nickname, post.user
  - else
    span.user-nickname[style='font-size: 1.6rem'] = post.user.nickname

  - if signed_in? && post_belongs_to_current_user?(post)
    = link_to 'Delete', post, method: :delete,
                              class: 'btn btn-primary submit-button--red',
                              style: 'float: right; font-size: 1.2rem; margin-left: 1rem;',
                              data: { confirm: 'Are you sure?' }

    = link_to 'Edit', edit_post_path(post), class: 'btn btn-primary submit-button',
                                            style: 'float: right; font-size: 1.2rem;'


  div[id="carouselIndicators#{post_index}" class='carousel slide'
      data-ride='carousel' data-interval='false']

    - if post.images.count > 1
      ol.carousel-indicators
        li.active[data-target="#carouselIndicators#{post_index}" data-slide-to='0']
        - (post.images.count-1).times do |t|
          li[data-target="#carouselIndicators#{post_index}" data-slide-to="#{t+1}"]

    div.carousel-inner
      - post.images.each_with_index do |img, i|
        - if i == 0
          div.carousel-item.active
            - unless img.content_type == 'image/gif'
              = image_tag(img.variant(resize_to_fill: [500, 500]), class: 'd-block w-100')
            - else  
              = image_tag(img, class: 'd-block w-100', height: 500, width: 500)
        - else
          div.carousel-item
            - unless img.content_type == 'image/gif'
              = image_tag(img.variant(resize_to_fill: [500, 500]), class: 'd-block w-100')
            - else  
              = image_tag(img, class: 'd-block w-100', height: 500, width: 500)

      - if post.images.count > 1
        a.carousel-control-prev[href="#carouselIndicators#{post_index}" role='button'
                                data-slide='prev']
          span.carousel-control-prev-icon[area-hidden='true']
          span.sr-only Previous

        a.carousel-control-next[href="#carouselIndicators#{post_index}" role='button'
                                data-slide='next']
          span.carousel-control-next-icon[area-hidden='true']     
          span.sr-only Next
  div.w-100
  div.likes-section
    - if signed_in?
      - unless post.liked_by_user?(current_user)
        = button_to 'Like', post_like_path(post), class: 'btn btn-primary like-button'
      - else
        = button_to 'Unlike', post_unlike_path(post), method: :delete,
                                                      class: 'btn btn-primary unlike-button'
    - if post.likes.any?
      = link_to "Likes: #{post.likes.size}", post_likes_path(post)
    - else
      = content_tag(:p, "Likes: 0")
        

  div.post-content
    p = post.content
    hr
    div.created-at
      b = post.created_at_formatted
  - if post.comments.any?
    div.comments-section
      - if page == :all_posts || page == :user_posts
        - if post.comments.size > 3
          p = link_to "All comments(#{post.comments.size})", post, class: 'manipulate-comment-link'
        - post.comments.sort_by(&:created_at).last(3).each do |c|
          div.comment
            = render 'users/avatar', user: c.user, side: 40,   link: true
            span.comment-user-nickname 
              = link_to c.user.nickname, c.user
              | : 
              = c.content
            - if comment_belongs_to_current_user?(c)
              br
              = link_to 'Edit', edit_post_comment_path(post, c), page: :edit,
                                                                 class: 'manipulate-comment-link',
                                                                 style: 'margin-right: 0.5rem'

              = link_to 'Delete', post_comment_path(post, c), method: :delete,
                                                              data: { confirm: 'Are you sure?' },
                                                              class: 'manipulate-comment-link'
          hr    

      - elsif page == :post
        - post.comments.sort_by(&:created_at).each do |c|
          div.comment
            = render 'users/avatar', user: c.user, side: 40,   link: true
            span.comment-user-nickname 
              = link_to c.user.nickname, c.user
              | : 
              = c.content
            - if comment_belongs_to_current_user?(c)
              br
              = link_to 'Edit', edit_post_comment_path(post, c), page: :edit,
                                                                 style: 'margin-right: 0.5rem',
                                                                 class: 'manipulate-comment-link'

              = link_to 'Delete', post_comment_path(post, c), method: :delete,
                                                              data: { confirm: 'Are you sure?' },
                                                              class: 'manipulate-comment-link'
          hr

  - if signed_in?
    = render 'comments/form', url: post_comments_path(post),
                              model: [post, Comment.new],
                              page: :new
  - else
    p[style='font-size: 1.4rem; margin-top: 1rem']
      = link_to 'Sign in', sign_in_path
      |  to leave comments

app/views/posts/edit.html.slim
div.row.justify-content-center
  h1 Update Post
  div.w-100
  = render 'posts/form', post: @post,
                         url: @post,
                         method: :patch,
                         page: :edit

app/views/posts/index.html.slim
div.row.justify-content-center
  h1 All Posts
  div.w-100
  div.col-9
    div.all-posts-wrap
      - if @posts.any?
        == pagy_bootstrap_nav(@pagy)
      - @posts.each_with_index do |post, index|
        = render 'posts/post', post: post,
                               post_index: index,
                               avatar_link: true,
                               page: :all_posts
      - if @posts.any?
        == pagy_bootstrap_nav(@pagy)                         

app/views/posts/likes.html.slim
div.row.justify-content-center
  h1 Users that liked post
  div.w-100
  div.col-9
    div.all-users-wrap
      == pagy_bootstrap_nav(@pagy)
      - @users.each do |user|
        = render user
      == pagy_bootstrap_nav(@pagy)          

app/views/posts/new.html.slim
div.row.justify-content-center
  h1 Create New Post
  div.w-100
  = render 'posts/form', post: @post,
                         url: create_post_path,
                         method: :post,
                         page: :new

app/views/posts/show.html.slim
div.row.justify-content-center
  div.col-9
    = render 'posts/post', post: @post,
                           post_index: 1,
                           avatar_link: true,
                           page: :post