config/routes.rb
Rails.application.routes.draw do
  # root path
  root 'posts#index'

  # users
  get '/sign-up', to: 'users#new'
  post '/sign-up', to: 'users#create'

  get '/edit-account', to: 'users#edit'
  patch '/edit-account', to: 'users#update'

  delete '/delete-avatar', to: 'users#delete_avatar'
  delete '/delete-account', to: 'users#destroy'

  get '/feed', to: 'users#feed'

  resources :users, only: %i[index show] do
    member do
      get 'followings'
      get 'followers'
    end
  end

  # sessions
  get '/sign-in', to: 'sessions#new'
  post '/sign-in', to: 'sessions#create'
  delete '/sign-out', to: 'sessions#destroy'

  # posts
  get '/create-post', to: 'posts#new'
  post '/create-post', to: 'posts#create'

  resources :posts, only: %i[index
                             show
                             edit
                             update
                             destroy] do
    # post comments
    resources :comments, only: %i[edit create update destroy]

    # post likes
    post '/like', to: 'likes#create'
    delete '/unlike', to: 'likes#destroy'
    get '/likes', to: 'posts#likes'
  end

  # followings
  post '/follow/:id', to: 'followings#create', as: 'follow_user'
  delete '/unfollow/:id', to: 'followings#destroy', as: 'unfollow_user'
end

app/views/layouts/_bootstrap.html.erb
<link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
      integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
      crossorigin="anonymous">

<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"
        integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+"
        crossorigin="anonymous"></script>

app/views/layouts/_navbar.html.erb
<nav id='navbar' class="navbar navbar-expand-md navbar-light bg-light-green sticky-top">
  <div class="navbar w-100 navbar-content-wrap">
    <%= link_to 'InstaRails', root_path, id: 'logo', class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
                                   data-target="#coll-navbar" aria-controls="coll-navbar"
                                   aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="coll-navbar">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'All Posts', posts_path, class: 'nav-link' %>
        </li>
        <%- if signed_in? %>
          <li class="nav-item">
            <!-- <a class="nav-link" href=feed_path>Feed</a> -->
            <%= link_to 'Feed', feed_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'New Post', create_post_path, class: 'nav-link' %>
          </li>
        <%- end %>
      </ul>
      <%- if signed_in? %>
        <ul id='coll-navbar__right' class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to 'All Users', users_path, class: 'nav-link' %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#"
               data-toggle="dropdown" aria-expanded="false">
              <%= current_user.nickname %>
            </a>
            <div class="dropdown-menu">
              <%= link_to 'Account', current_user, class: 'dropdown-item text-decoration-none' %>
              <%= link_to 'Settings', edit_account_path, class: 'dropdown-item text-decoration-none' %>
              <%= link_to 'Sign Out', sign_out_path, method: :delete,
                                                     class: 'dropdown-item text-decoration-none',
                                                     data: { confirm: 'Are you sure?'} %>
            </div>
          </li>
        </ul>
      <%- else %>
        <ul id='coll-navbar__right' class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to 'Sign In', sign_in_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', sign_up_path, class: 'nav-link' %>
          </li>
        </ul>
      <%- end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instarails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag asset_path('favicon.png') %>

    <!-- font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Josefin+Sans">

    <!-- bootstrap 4.6 -->
    <%= render 'layouts/bootstrap' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%- flash.each do |k, v| %>
        <%= content_tag(:div, v, class: "alert alert-#{k}") %>
      <%- end %>  
      
      <%= yield %>
    </div>

  </body>
</html>